### PR TITLE
Python packages should not install literal 'src'

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
See e.g. https://build.opensuse.org/request/show/742273 .  I've seen this a few times in packages , but this is the first time in an existing openSUSE package.

It is happening because Python guidelines are suggesting to move code into the `src` subdirectory, and authors are doing that but not getting the rest of the metadata correct, because it 'works' when they have made 'src' installed as the package name, and they stop there.

**Comment by jayvdb** [comment]
And the package name `src` is reserved because of this; see https://pypi.org/project/src/

**Comment by scarabeusiv** [comment]
We are rebasing this to be integrated better in upstream.
Could you please create commit as a followup on https://github.com/rpm-software-management/rpmlint/commit/5578ac006590386da3d274443c1c3d4b69757e0e (see the opensuse branch there)

**Comment by scarabeusiv** [comment]
Merged in the 2.0 checker for later usage.

**Pull request closed without merging**
