### PR TITLE
Cron whitelisting and some refactoring of security related checks

### PR DESCRIPTION
**Pull request by mgerstner**
This adds a new more generic approach to implement whitelisting restrictions. Along with it a new check for cron job files is introduced. I also tried so harmonize the code of the security related checks a bit.

The new check won't be active right away. There's currently no badness configured, also rpmlint/config needs to be adjusted and the new whitelisting file needs to be embedded into rpmlint-mini.

### CODE REVIEW

**Comment by mgerstner** [comment]
@jsegitz @maltek 
Could you please help reviewing this PR, thanks!

**Comment by mgerstner** [comment]
I force-pushed some adjustments to satisfy flake...

**Comment by mgerstner** [comment]
And force-pushed a bugfix for a bug I introducing trying to satisfy flake ... :-/

**Comment by maltek** [comment]
Looks good to me!

**Comment by jsegitz** [comment]
I would prefer having on PR for the new cron feature and one for the refactoring, but that is really a minor nitpick. Thank you for this nice functionality, I'll merge it

**Pull request merged**
