### PR TITLE
rpmlint: allow /usr/share/licenses in shared library packages (used b…

### PR DESCRIPTION
**Pull request by DimStar77**
…y %license)

### CODE REVIEW

**Comment by dirkmueller** [comment]
The commit message and the change don't seem to be in sync.. can you point to the testcase?

**Comment by DimStar77** [comment]
What's not in sync?

The commit says to allow /usr/share/licenses in slpp packages, and the diff adds /usr/share/licenses to sysdirs

Will setup a test project for this very minimalistic change; sounded too straight forward to me apparently

**Comment by DimStar77** [comment]
setup home:dimstar:gh15 for this issue (which I somewhat lost track off - shame)

there are two build targets:
openSUSE_Tumbleweed: building against 'stock' rpmlint, the build log shows the warning I attempt to fix
openSUSE_Tumbleweed_fixed: building against patched rpmlint (with this pr applied)

build logs (and excertp)

openSUSE_Tumbleweed: https://build.opensuse.org/package/live_build_log/home:dimstar:gh15/libproxy/openSUSE_Tumbleweed/x86_64

```
[   94s] libproxy1.x86_64: W: shlib-policy-nonversioned-dir /usr/share/licenses
[   94s] Your shared library package contains non-versioned directories. Those will not
[   94s] allow to install multiple versions of the package in parallel.
```

openSUSE_Tumbleweed_fixed: https://build.opensuse.org/package/live_build_log/home:dimstar:gh15/libproxy/openSUSE_Tumbleweed_fixed/x86_64

=> above warning about /usr/share/licenses is not printed

**Comment by dirkmueller** [comment]
Thanks, I'll look at this shortly

**Comment by dirkmueller** [comment]
Merged manually (the branch merged confused things). thanks.

**Pull request closed without merging**
